### PR TITLE
Extend CLI to provide separate file for profiling

### PR DESCRIPTION
**Pull request by jakobrobert**
The CLI is changed for the new buffer based API as discussed in #8.

There are two ways for profiling now, either provide a separate file with only noise by the param --profile / -p or provide time indices as usual to take part of the input file for profiling.

Added new tests as well, they can be found in test/separate-track-for-profiling. Run the corresponding run.sh bash scripts.

As well, added Visual Studio code to gitignore.

### CODE REVIEW

**Comment by tals** [comment]
Awesome!
Code itself looks good, but can you use smaller test files? the ones you've added are a couple of mbs each, and this adds up quickly.

**Comment by jakobrobert** [comment]
Oh, I understand. Should I just add another commit to my branch? Or is this a problem because then the files are still contained in the history? Rather amend my last commit?

**Comment by tals** [comment]
you can amend it or I can squash it

**Comment by jakobrobert** [comment]
It's fixed now. 82 KB rather than 2 MB, quite a difference :D

**Comment by tals** [comment]
lol

**Pull request merged**
